// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbifrtnyzcprxbzxaqyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiaWZydG55emNwcnhienhhcXl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTMyMjgsImV4cCI6MjA3MjA2OTIyOH0.nxY_VtnokmRjk3ei0WmopwEwZqSmbUwqPlaphXCZlsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});